from question2 import Graph

ethiopia_graph_weighted = [
    ("Kartum", [("Humera", 21), ("Metema", 19)]),
    ("Humera", [("Kartum", 21), ("Shire", 8), ("Gondar", 9)]),
    ("Metema", [("Kartum", 19), ("Gondar", 7)]),
    ("Shire", [("Humera", 8), ("Axum", 2), ("Debarke", 9)]),
    ("Gondar", [("Humera", 9), ("Metema", 7), ("Debarke", 4), ("Azezo", 1)]),
    ("Axum", [("Shire", 2), ("Adwa", 1), ("Asmera", 5)]),
    ("Debarke", [("Shire", 9), ("Gondar", 4)]),
    ("Adwa", [("Axum", 1), ("Adigrat", 4), ("Mekelle", 7)]),
    ("Adigrat", [("Adwa", 4), ("Mekelle", 4), ("Asmera", 4)]),
    ("Asmera", [("Axum", 5), ("Adigrat", 4)]),
    ("Mekelle", [("Adwa", 7), ("Adigrat", 4), ("Sekota", 9), ("Alamata", 5)]),
    ("Sekota", [("Mekelle", 9), ("Alamata", 6), ("Lalibela", 9)]),
    ("Alamata", [("Mekelle", 5), ("Sekota", 6),
     ("Woldia", 3), ("Samara", 11)]),
    ("Lalibela", [("Sekota", 9), ("Debre Tabor", 8), ("Woldia", 7)]),
    ("Woldia", [("Alamata", 3), ("Lalibela", 7), ("Samara", 8), ("Dessie", 6)]),
    ("Samara", [("Alamata", 11), ("Woldia", 8),
     ("Fanti Rasu", 7), ("Gabi Rasu", 9)]),
    ("Fanti Rasu", [("Samara", 7), ("Kilbet Rasu", 6)]),
    ("Debre Tabor", [("Lalibela", 8), ("Bahir Dar", 4)]),
    ("Bahir Dar", [("Debre Tabor", 4), ("Azezo", 7),
     ("Finote Selam", 6), ("Injibara", 4), ("Metekel", 11)]),
    ("Azezo", [("Bahir Dar", 7), ("Metema", 7), ("Gondar", 1)]),
    ("Finote Selam", [("Bahir Dar", 6), ("Injibara", 2), ("Debre Markos", 3)]),
    ("Injibara", [("Bahir Dar", 4), ("Finote Selam", 2)]),
    ("Debre Markos", [("Finote Selam", 3), ("Debre Sina", 17)]),
    ("Debre Sina", [("Debre Markos", 17), ("Debre Birhan", 2), ("Kemise", 6)]),
    ("Debre Birhan", [("Debre Sina", 2), ("Addis Ababa", 5)]),
    ("Kemise", [("Debre Sina", 6), ("Dessie", 4)]),
    ("Dessie", [("Kemise", 4), ("Woldia", 6)]),
    ("Addis Ababa", [("Debre Birhan", 5), ("Ambo", 5), ("Adama", 3)]),
    ("Ambo", [("Addis Ababa", 5), ("Nekemte", 9), ("Wolkite", 6)]),
    ("Adama", [("Addis Ababa", 3), ("Matahara", 3), ("Batu", 4), ("Assella", 4)]),
    ("Matahara", [("Adama", 3), ("Awash", 1)]),
    ("Awash", [("Matahara", 1), ("Gabi Rasu", 5), ("Chiro", 4)]),
    ("Gabi Rasu", [("Awash", 5), ("Samara", 9)]),
    ("Chiro", [("Awash", 4), ("Dire Dawa", 8)]),
    ("Dire Dawa", [("Chiro", 8), ("Harar", 4)]),
    ("Harar", [("Dire Dawa", 4), ("Babile", 2)]),
    ("Babile", [("Harar", 2), ("Jigjiga", 3), ("Goba", 28)]),
    ("Jigjiga", [("Babile", 3), ("Dega Habur", 5)]),
    ("Dega Habur", [("Jigjiga", 5), ("Kebri Dehar", 6)]),
    ("Kebri Dehar", [("Dega Habur", 6), ("Werder", 6), ("Goder", 5)]),
    ("Goba", [("Babile", 28), ("Sof Oumer", 6), ("Bale", 18)]),
    ("Sof Oumer", [("Goba", 6), ("Bale", 23), ("Goder", 23)]),
    ("Bale", [("Goba", 18), ("Sof Oumer", 23), ("Liben", 11), ("Dodolla", 13)]),
    ("Dodolla", [("Bale", 13), ("Shashemene", 3), ("Assasa", 1)]),
    ("Shashemene", [("Dodolla", 3),
     ("Hawassa", 1), ("Hossana", 7), ("Batu", 3)]),
    ("Hawassa", [("Shashemene", 1), ("Dilla", 3)]),
    ("Dilla", [("Hawassa", 3), ("Bule Hora", 4)]),
    ("Bule Hora", [("Dilla", 4), ("Yabello", 3)]),
    ("Yabello", [("Bule Hora", 3), ("Konso", 3), ("Moyale", 6)]),
    ("Konso", [("Yabello", 3), ("Arba Minch", 4)]),
    ("Arba Minch", [("Konso", 4), ("Wolaita Sodo", 4), ("Basketo", 10)]),
    ("Wolaita Sodo", [("Arba Minch", 4), ("Hossana", 4), ("Dawaro", 6)]),
    ("Hossana", [("Wolaita Sodo", 4), ("Shashemene", 7), ("Worabe", 2)]),
    ("Moyale", [("Yabello", 6), ("Nairobi", 22)]),
    ("Basketo", [("Arba Minch", 10), ("Bench Maji", 5)]),
    ("Bench Maji", [("Basketo", 5), ("Juba", 22)]),
    ("Dawaro", [("Wolaita Sodo", 6), ("Bonga", 10)]),
    ("Bonga", [("Dawaro", 10), ("Jimma", 4),
     ("Mezan Teferi", 4), ("Tepi", 8)]),
    ("Jimma", [("Bonga", 4), ("Bedelle", 7), ("Wolkite", 8)]),
    ("Mezan Teferi", [("Bonga", 4), ("Tepi", 4)]),
    ("Tepi", [("Bonga", 8), ("Mezan Teferi", 4), ("Gore", 9)]),
    ("Bedelle", [("Jimma", 7), ("Nekemte", 4), ("Gore", 6)]),
    ("Nekemte", [("Bedelle", 4), ("Gimbi", 4), ("Ambo", 9)]),
    ("Gimbi", [("Nekemte", 4), ("Dembi Dolo", 6)]),
    ("Dembi Dolo", [("Gimbi", 6), ("Assosa", 12), ("Gambella", 4)]),
    ("Gambella", [("Dembi Dolo", 4), ("Gore", 5)]),
    ("Gore", [("Gambella", 5), ("Tepi", 9), ("Bedelle", 6)]),
    ("Wolkite", [("Jimma", 8), ("Ambo", 6), ("Worabe", 5)]),
    ("Worabe", [("Wolkite", 5), ("Hossana", 2), ("Buta Jirra", 2)]),
    ("Buta Jirra", [("Worabe", 2), ("Batu", 2)]),
    ("Batu", [("Buta Jirra", 2), ("Shashemene", 3), ("Adama", 4)]),
    ("Assasa", [("Dodolla", 1)])
]

graph = Graph()

for from_city, to_cities in ethiopia_graph_weighted:
    for to_city, cost in to_cities:
        graph.add_edge(from_city, to_city, cost)

print("Uniform Cost Search Path:",
      graph.uniform_cost_search("Addis Ababa", "Lalibela"))
