from question3 import Graph

ethiopia_graph_with_heuristics = [
    ("Kartum", [("Humera", 21), ("Metema", 19)], 81),
    ("Humera", [("Kartum", 21), ("Shire", 8), ("Gondar", 9)], 65),
    ("Metema", [("Kartum", 19), ("Gondar", 7), ("Azezo", 7)], 62),
    ("Shire", [("Humera", 8), ("Axum", 2), ("Debarke", 9)], 67),
    ("Axum", [("Shire", 2), ("Adwa", 1), ("Asmera", 5)], 66),
    ("Adwa", [("Axum", 1), ("Adigrat", 4), ("Mekelle", 7)], 65),
    ("Adigrat", [("Adwa", 4), ("Mekelle", 4), ("Asmera", 4)], 62),
    ("Mekelle", [("Adwa", 7), ("Adigrat", 4),
     ("Sekota", 9), ("Alamata", 5)], 58),
    ("Sekota", [("Mekelle", 9), ("Alamata", 6), ("Lalibela", 9)], 59),
    ("Lalibela", [("Sekota", 9), ("Debre Tabor", 8), ("Woldia", 7)], 57),
    ("Debre Tabor", [("Lalibela", 8), ("Bahir Dar", 4), ("Gondar", 6)], 52),
    ("Bahir Dar", [("Debre Tabor", 4), ("Azezo", 7),
     ("Finote Selam", 6), ("Injibara", 4), ("Metekel", 11)], 48),
    ("Azezo", [("Bahir Dar", 7), ("Metema", 7), ("Gondar", 1)], 55),
    ("Gondar", [("Humera", 9), ("Metema", 7),
     ("Debarke", 4), ("Azezo", 1), ("Debre Tabor", 6)], 56),
    ("Debarke", [("Shire", 9), ("Gondar", 4)], 60),
    ("Asmera", [("Axum", 5), ("Adigrat", 4)], 68),
    ("Alamata", [("Mekelle", 5), ("Sekota", 6),
     ("Woldia", 3), ("Samara", 11)], 59),
    ("Woldia", [("Alamata", 3), ("Lalibela", 7),
     ("Samara", 8), ("Dessie", 6)], 50),
    ("Samara", [("Alamata", 11), ("Woldia", 8),
     ("Fanti Rasu", 7), ("Gabi Rasu", 9)], 42),
    ("Fanti Rasu", [("Samara", 7), ("Kilbet Rasu", 6)], 49),
    ("Kilbet Rasu", [("Fanti Rasu", 6)], 55),
    ("Dessie", [("Woldia", 6), ("Kemise", 4)], 44),
    ("Kemise", [("Dessie", 4), ("Debre Sina", 7)], 40),
    ("Debre Markos", [("Finote Selam", 3),
     ("Debre Sina", 17), ("Addis Ababa", 13)], 39),
    ("Finote Selam", [("Bahir Dar", 6),
     ("Injibara", 2), ("Debre Markos", 3)], 42),
    ("Injibara", [("Bahir Dar", 4), ("Finote Selam", 2)], 44),
    ("Metekel", [("Bahir Dar", 11)], 59),
    ("Debre Sina", [("Debre Markos", 17),
     ("Debre Birhan", 2), ("Kemise", 7)], 33),
    ("Debre Birhan", [("Debre Sina", 2), ("Addis Ababa", 5)], 31),
    ("Addis Ababa", [("Debre Markos", 13),
     ("Debre Birhan", 5), ("Ambo", 5), ("Adama", 3)], 26),
    ("Ambo", [("Addis Ababa", 5), ("Nekemte", 9), ("Wolkite", 6)], 31),
    ("Adama", [("Addis Ababa", 3), ("Matahara", 3),
     ("Batu", 4), ("Assella", 4)], 23),
    ("Matahara", [("Adama", 3), ("Awash", 1)], 23),
    ("Awash", [("Matahara", 1), ("Gabi Rasu", 5), ("Chiro", 4)], 21),
    ("Gabi Rasu", [("Awash", 5), ("Samara", 9)], 32),
    ("Chiro", [("Awash", 4), ("Dire Dawa", 8)], 31),
    ("Dire Dawa", [("Chiro", 8), ("Harar", 4)], 31),
    ("Harar", [("Dire Dawa", 4), ("Babile", 2)], 35),
    ("Babile", [("Harar", 2), ("Jigjiga", 3), ("Goba", 28)], 37),
    ("Jigjiga", [("Babile", 3), ("Dega Habur", 5)], 40),
    ("Dega Habur", [("Jigjiga", 5), ("Kebri Dehar", 6)], 45),
    ("Kebri Dehar", [("Dega Habur", 6), ("Werder", 6), ("Gode", 5)], 40),
    ("Werder", [("Kebri Dehar", 6)], 46),
    ("Gode", [("Kebri Dehar", 5), ("Dollo", 17), ("Mokadisho", 22)], 35),
    ("Dollo", [("Gode", 17), ("Moyale", 18)], 18),
    ("Mokadisho", [("Gode", 22), ("Moyale", 40)], 40),
    ("Goba", [("Babile", 28), ("Sof Oumer", 6), ("Robe", 18)], 40),
    ("Sof Oumer", [("Goba", 6), ("Robe", 23), ("Gode", 23)], 45),
    ("Robe", [("Goba", 18), ("Sof Oumer", 23),
     ("Liben", 11), ("Dodolla", 13)], 22),
    ("Liben", [("Robe", 11), ("Moyale", 11)], 40),
    ("Dodolla", [("Robe", 13), ("Shashemene", 3), ("Assasa", 1)], 19),
    ("Assasa", [("Dodolla", 1)], 18),
    ("Shashemene", [("Dodolla", 3), ("Hawassa", 1),
     ("Hossana", 7), ("Batu", 3)], 16),
    ("Hawassa", [("Shashemene", 1), ("Dilla", 3)], 15),
    ("Dilla", [("Hawassa", 3), ("Bule Hora", 4)], 12),
    ("Bule Hora", [("Dilla", 4), ("Yabello", 2)], 8),
    ("Yabello", [("Bule Hora", 2), ("Konso", 3), ("Moyale", 6)], 6),
    ("Konso", [("Yabello", 3), ("Arba Minch", 4)], 9),
    ("Arba Minch", [("Konso", 4), ("Wolaita Sodo", 4), ("Basketo", 10)], 13),
    ("Wolaita Sodo", [("Arba Minch", 4), ("Hossana", 4), ("Dawaro", 6)], 17),
    ("Hossana", [("Wolaita Sodo", 4), ("Shashemene", 7), ("Worabe", 2)], 21),
    ("Moyale", [("Yabello", 6), ("Liben", 11),
     ("Dollo", 18), ("Mokadisho", 40), ("Nairobi", 22)], 0),
    ("Nairobi", [("Moyale", 22)], 22),
    ("Basketo", [("Arba Minch", 10), ("Bench Maji", 5)], 23),
    ("Bench Maji", [("Basketo", 5), ("Juba", 22)], 28),
    ("Juba", [("Bench Maji", 22)], 50),
    ("Dawaro", [("Wolaita Sodo", 6), ("Bonga", 10)], 23),
    ("Bonga", [("Dawaro", 10), ("Jimma", 4),
     ("Mezan Teferi", 4), ("Tepi", 8)], 33),
    ("Jimma", [("Bonga", 4), ("Bedelle", 7), ("Wolkite", 8)], 33),
    ("Mezan Teferi", [("Bonga", 4), ("Tepi", 4)], 37),
    ("Tepi", [("Bonga", 8), ("Mezan Teferi", 4), ("Gore", 9)], 41),
    ("Bedelle", [("Jimma", 7), ("Nekemte", 4), ("Gore", 6)], 40),
    ("Nekemte", [("Bedelle", 4), ("Gimbi", 4), ("Ambo", 9)], 39),
    ("Gimbi", [("Nekemte", 4), ("Dembi Dolo", 6), ("Assosa", 8)], 43),
    ("Dembi Dolo", [("Gimbi", 6), ("Assosa", 12), ("Gambella", 4)], 49),
    ("Assosa", [("Gimbi", 8), ("Dembi Dolo", 12)], 51),
    ("Gambella", [("Dembi Dolo", 4), ("Gore", 5)], 51),
    ("Gore", [("Gambella", 5), ("Tepi", 9), ("Bedelle", 6)], 46),
    ("Wolkite", [("Jimma", 8), ("Ambo", 6),
     ("Worabe", 5), ("Buta Jirra", 4)], 25),
    ("Worabe", [("Wolkite", 5), ("Hossana", 2), ("Buta Jirra", 2)], 22),
    ("Buta Jirra", [("Wolkite", 4), ("Worabe", 2), ("Batu", 2)], 21),
    ("Batu", [("Buta Jirra", 2), ("Shashemene", 3), ("Adama", 4)], 19),
    ("Assella", [("Adama", 4)], 22)
]

graph = Graph()

for city, neighbors, heuristic in ethiopia_graph_with_heuristics:
    for neighbor, weight in neighbors:
        graph.add_edge(city, neighbor, weight)
    graph.set_heuristic(city, heuristic)


print("A* Search Path:", graph.a_star_search("Addis Ababa", "Moyale"))
